basePath: /api/v1
info:
  contact: {}
paths:
  /api/icg/defineLBConfig:
    post:
      consumes:
      - application/json
      parameters:
      - description: title
        in: body
        name: title
        required: true
        schema:
          type: string
      - description: body
        in: body
        name: body
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "201":
          description: ""
        "400":
          description: ""
      summary: defines load balance policy that applies to traffic intended for a
        service after routing has occurred.
  /api/icg/weightConfig:
    post:
      consumes:
      - application/json
      parameters:
      - description: title
        in: body
        name: title
        required: true
        schema:
          type: string
      - description: body
        in: body
        name: body
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "201":
          description: ""
        "400":
          description: ""
      summary: defines weight policies that apply to traffic intended for a service
        after routing has occurred.
  /example/helloworld:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
      tags:
      - example
  /testapi/get-string-by-int/{some_id}:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: ""
        "404":
          description: ""
      summary: lists istio configurations of intio-gateway, virtual service, and destination
        rules.
swagger: "2.0"
