basePath: /
definitions:
  main.lb:
    properties:
      lb:
        type: integer
      ns:
        example: istio-test
        type: string
      svcname:
        example: catalog
        type: string
      version:
        example: v1
        type: string
    type: object
  main.weights:
    properties:
      ns:
        example: istio-test
        type: string
      svcname:
        example: catalog
        type: string
      'versions example:':
        items:
          type: string
        type: array
      weights:
        items:
          type: integer
        type: array
    type: object
info:
  contact: {}
paths:
  /api/icg/istioConfig:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: ""
      summary: lists istio configurations of intio-gateway, virtual service, and destination
        rules.
      tags:
      - Istio Resouce Config
  /api/icg/lbConfig:
    post:
      consumes:
      - application/json
      parameters:
      - description: new LB policy to apply to service
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/main.lb'
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: ""
      summary: defines load balance policy that applies to traffic intended for a
        service after routing has occurred.
      tags:
      - Istio Resouce Config
  /api/icg/weightConfig:
    post:
      consumes:
      - application/json
      parameters:
      - description: new weights config
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/main.weights'
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: ""
      summary: defines weight policies that apply to traffic intended for a service
        after routing has occurred.
      tags:
      - Istio Resouce Config
  /example/helloworld:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
      tags:
      - example
swagger: "2.0"
